version: '2'
services:
  prerender:
    build: .
    working_dir: /home/prerender
    volumes:
      - ./:/home/prerender
    command: bash -c "[ -d 'node_modules' ] || npm i && node server.js"
    environment:
      DOMAINS: '[]'
      FOLLOW_REDIRECTS: 1
    ports:
      - 3000:3000